### ISSUE TITLE
Negative value of bounding box coordinate in json

### ISSUE THREAD

**Issue by DevKiHyun** [clovaai/lookwhostalking#6]
I found some negative value in bbox of json files.

I wonder that what this negative values mean.

**Comment by 117kyjin** [comment]
In json, elements of bbox list represent [x1, y1, x2, y2], where (x1, y1) is the top-left coordinate and (x2, y2) is the bottom-right coordinate. The coordinates are normalized with respect to frame size, where (0.0, 0.0) corresponds to the top-left, and (1.0, 1.0) corresponds to bottom-right.

Some of the faces are on the edges of the video frame, and we draw bboxes over the video frame with zero-padded edges. So, you can find some negative values in json.
<img width="150" alt="image" src="https://github.com/clovaai/lookwhostalking/assets/20121380/ce46e756-b3f9-4af3-88e1-9d7a96eac1a4">
