### ISSUE TITLE
how to download the dataset ?

### ISSUE THREAD

**Issue by Ontheway361** [clovaai/lookwhostalking#7]

**Comment by jun297** [comment]
same issue here

**Comment by Ontheway361** [comment]
您好，我已经收到您的邮件，谢谢。

**Comment by 117kyjin** [comment]
- You can download YouTube videos using https://youtube-dl.org/, with YouTube video-ids that were provided in json/*.

```
youtube-dl --extract-audio --audio-format mp3 <video URL> # You can download mp3 directly from youtube 
```

- Also, I would like to share the dataset, but due to copyright issue, I cannot.

**Comment by Ontheway361** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Hi, my dear guys, what’s ur problem ? Please be brave, do not care the fuck copyright, just share it.Here we go.
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                2459699580
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        06/7/2023 09:34
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [clovaai/lookwhostalking] how to download the dataset ? (Issue #7)
        
      
    
  
  

You can download YouTube videos using https://youtube-dl.org/, with YouTube video-ids that were provided in json/*.

youtube-dl --extract-audio --audio-format mp3 <video URL> # You can download mp3 directly from youtube 


Also, I would like to share the dataset, but due to copyright issue, I cannot.


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Ontheway361** [comment]
您好，我已经收到您的邮件，谢谢。
